name: gcunhistorical
region: syd

# Explicitly specify buildpack features
features:
  - buildpack-stack=ubuntu-22

# Single service configuration - Express serves both API and Angular static files
services:
  - name: gcunhistorical-api
    github:
      repo: RalphLavelle/GLUnhistorical
      branch: master
      deploy_on_push: true
    source_dir: /
    # Explicitly specify Node.js buildpack
    environment_slug: node-js
    # Build command: install dependencies and build both frontend and backend
    # Using npm run build ensures ng command is found via npm scripts (which add node_modules/.bin to PATH)
    build_command: |
      set -e
      echo "Installing frontend dependencies..."
      cd frontend && npm install --legacy-peer-deps
      echo "Building frontend (production)..."
      npm run build -- --configuration production
      echo "Installing backend dependencies..."
      cd ../backend && npm install
      echo "Building backend..."
      npx tsc
    # Run command: start the Express server (which serves both API and Angular static files)
    run_command: cd backend && npm start
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/month - smallest option (512 MB RAM, 1 vCPU)
    http_port: 3000
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        scope: RUN_TIME
        type: SECRET  # Set this via DigitalOcean dashboard - don't commit secrets
      - key: MONGODB_DB_NAME
        value: gcunhistorical
      - key: PORT
        value: "3000"


