name: gcobscura
region: sfo  # Change to your preferred region (nyc, sfo, ams, sgp, etc.)

# Single service configuration - Express serves both API and Angular static files
services:
  - name: gcobscura-api
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME  # Update with your GitHub repo
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: |
      cd frontend && npm install && npm run build && cd ../backend && npm install && npm run build
    run_command: cd backend && npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/month - smallest option (512 MB RAM, 1 vCPU)
    http_port: 3000
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        scope: RUN_TIME
        type: SECRET  # Set this via DigitalOcean dashboard - don't commit secrets
      - key: MONGODB_DB_NAME
        value: gcobscura
      - key: PORT
        value: "3000"


